### ISSUE TITLE
Galacticraft RPC Crash When Going Through Aroma's Dimensional World Portal

### ISSUE THREAD

**Issue by janagyjr** [BooLaLaEnterprises/TCGs-Just-for-Fun-Pack#1]
Reported to Galacticraft RPC
https://github.com/JoeZwet/Galacticraft-RPC/issues/17

**Comment by janagyjr** [comment]
Current workaround: disable Galacticraft RPC.

**Comment by JustPyrrha** [comment]
A hotfix is in development, I'll post here when it's out.

**Comment by janagyjr** [comment]
Thanks for the quick response!

**Comment by janagyjr** [comment]
This issue is closed with the issuance of [this patch](https://github.com/JoeZwet/Galacticraft-RPC/commit/60a9544984555cad1eb0e90068506009e2c1bb02) to Galacticraft RPC. The mod will be re-enabled in the next pack release.
